"""Generate the RAW type contract from Snowflake's information_schema (MLB-208).

WHAT THIS EXISTS FOR. `load_parquet_to_duckdb.py` pins DuckDB types from the
dump manifest rather than inferring them from parquet, and its reasons are
load-bearing: Snowflake's arrow encoder narrows integers to the values
actually present (SEASON_YEAR arrives as SMALLINT), so an inferred schema
drifts as the league adds rows; and Snowflake FLOAT is 64-bit where DuckDB's
is 32, the trap that landed 553.7 as 553.5999755859375. The declared type is
the stable thing, so the declared type is what gets replayed.

That worked as long as a Snowflake account existed to ask. A local-first
extract has nothing to ask, so the declared types have to live in the repo.
This script is how they get there.

GENERATED, NOT AUTHORED -- and the distinction is the point. A hand-typed
schema is one person's afternoon frozen into a file that looks authoritative.
This reads the warehouse's own catalog and stamps WHICH catalog it read into
the artifact, so the next reader can tell a real contract from a plausible
one. (MLB-215's scar: a probe that answered an easier question than the one
asked, because nobody recorded what it had actually been pointed at.)

WHAT IS DELIBERATELY NOT STAMPED: the Snowflake account identifier. Database
and schema are generic names that describe the shape; the account is a
credential-adjacent identifier and this file is committed. Database + schema
answer "which catalog", which is the question that matters.

The artifact is the single engine-neutral authority for RAW column types, and
two one-sided tests assert against it -- tests/test_raw_schema_contract.py
(warehouse-marked: does Snowflake still match?) and
tests/test_local_raw_writer.py (pure: does the local writer still match?).
Neither is bidirectional, on purpose: they fail for different reasons on
different machines, and merging them would make the publicly-runnable half
require credentials.

WHY THE KEYS SAY `snowflake_type`. Because the vocabulary genuinely is
Snowflake's -- TEXT, NUMBER, VARIANT, TIMESTAMP_NTZ -- and
`load_parquet_to_duckdb.py` switches on those literals. Renaming the key
while keeping the vocabulary would make the file look neutral and mean
exactly the same thing, at the cost of a translation seam between contract
and manifest that can drift. One name across contract, manifest and loader
means there is nothing to keep in sync.

Read-only against Snowflake: information_schema, nothing else.

Usage (from the repo root):
    python tools/generate_raw_schema_contract.py
    python tools/generate_raw_schema_contract.py --check    # CI-style diff, no write
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import snowflake.connector

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from tools.dump_snowflake_raw_to_parquet import build_config  # noqa: E402

CONTRACT_PATH = REPO_ROOT / "config" / "raw_schema_contract.json"

# Bumped when the artifact's SHAPE changes (not when the warehouse's types
# change). Lets a reader tell "regenerated by a newer tool" from "the
# warehouse drifted".
GENERATOR_VERSION = 1

SOURCE_DATABASE = "ESPN_FANTASY"
SOURCE_SCHEMA = "RAW"


def describe_raw(cur, database, schema):
    """{table: [{name, snowflake_type, precision, scale}, ...]} in ordinal order.

    Ordinal order is captured rather than the CREATE TABLE literal's order,
    and they are NOT the same: BOX_SCORES' CREATE lists season_year first,
    but the deployed table's ordinal 1 is SCORING_PERIOD, because the table
    evolved after it was first created and later columns land last. The
    catalog knows the truth; the DDL in extract.py records an intention.
    """
    cur.execute(
        f"""
        select table_name, column_name, data_type,
               numeric_precision, numeric_scale
        from {database}.information_schema.columns
        where table_schema = %s
        order by table_name, ordinal_position
        """,
        (schema,),
    )
    tables = {}
    for table_name, column_name, data_type, precision, scale in cur.fetchall():
        tables.setdefault(table_name, []).append({
            "name": column_name,
            "snowflake_type": data_type,
            "precision": precision,
            "scale": scale,
        })
    return tables


def build_contract(tables, generated_at):
    return {
        "_comment": (
            "GENERATED by tools/generate_raw_schema_contract.py from the "
            "Snowflake information_schema -- do not hand-edit. This is the "
            "engine-neutral authority for RAW column types; the local parquet "
            "writer emits to it and load_parquet_to_duckdb.py pins DuckDB "
            "types from it. Regenerate rather than patch (MLB-208)."
        ),
        "generator": "tools/generate_raw_schema_contract.py",
        "generator_version": GENERATOR_VERSION,
        "generated_at": generated_at,
        "generated_from": {
            "database": SOURCE_DATABASE,
            "schema": SOURCE_SCHEMA,
            "catalog": "information_schema.columns",
        },
        "tables": {t: tables[t] for t in sorted(tables)},
    }


def _comparable(contract):
    """The parts a --check diff should care about: the types, not the stamp."""
    return contract["tables"]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="compare the warehouse against the committed contract "
                         "and exit non-zero on any difference; write nothing")
    ap.add_argument("--out", default=str(CONTRACT_PATH))
    args = ap.parse_args()

    out_path = Path(args.out)

    conn = snowflake.connector.connect(**build_config())
    cur = conn.cursor()
    try:
        tables = describe_raw(cur, SOURCE_DATABASE, SOURCE_SCHEMA)
    finally:
        cur.close()
        conn.close()

    if not tables:
        sys.exit(f"no columns found in {SOURCE_DATABASE}.{SOURCE_SCHEMA} -- "
                 f"refusing to write an empty contract")

    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    contract = build_contract(tables, generated_at)

    if args.check:
        if not out_path.exists():
            sys.exit(f"no contract at {out_path}; run without --check first")
        committed = json.loads(out_path.read_text())
        if _comparable(committed) == _comparable(contract):
            print(f"contract matches {SOURCE_DATABASE}.{SOURCE_SCHEMA} "
                  f"({len(tables)} tables)")
            return
        sys.exit(f"CONTRACT DRIFT: {out_path} no longer matches "
                 f"{SOURCE_DATABASE}.{SOURCE_SCHEMA}. Run without --check to "
                 f"regenerate, and review the diff before committing.")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(contract, indent=2) + "\n")

    columns = sum(len(c) for c in tables.values())
    print(f"{len(tables)} tables, {columns} columns "
          f"-> {out_path.relative_to(REPO_ROOT)}")
    print(f"generated from {SOURCE_DATABASE}.{SOURCE_SCHEMA} at {generated_at}")


if __name__ == "__main__":
    main()
